import { css } from '@emotion/react';
import Head from 'next/head';
import Header from '../components/Header';
import Layout from '../components/Layout';

const bodyStyle = css`
  background-color: rgb(175, 198, 204);
  height: 100vh;
`;

export default function About() {
  return (
    <div css={bodyStyle}>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <h1>About</h1>
        <p>This is the about page</p>
      </Layout>
    </div>
  );
}
