import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
// import { useEffect, useState } from 'react';
import Footer from '../components/Footer';
import Layout from '../components/Layout';
import Thailand from '../public/images/1.jpg';
import Amsterdam from '../public/images/3.jpg';
import London from '../public/images/5.jpg';
import Sunrise from '../public/images2/sunrise.jpg';

// import { getLocalStorage, setLocalStorage } from '../util/localStorage';

// import vercelLogo from '../public/vercel.svg';
const backgroundImage = css`
  background-color: rgb(163, 120, 87, 0.7);
  /* background-color: #f3f7f2; */
  /* margin-bottom: 0; */
`;
const heroStyle = css`
  background-image: url('/images2/womanCooking.jpg');
  background-size: cover;
  background-repeat: no-repeat;
  height: 70vh;
  width: 100vw;
`;

const heroTextStyle = css`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  align-content: center;
  height: 30vw;
  color: #f3f7f2;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
    Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  h1 {
    font-size: 60px;
  }
  p {
    font-size: 30px;
  }
`;
const bodyStyle = css`
  /* margin: 30px; */
`;
const tourSectionStyle = css`
  display: flex;
  justify-content: flex-start;
  width: 100vw;
`;
const textTourSectionStyle = css`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  width: 45vw;
  margin: 50px;
  color: rgb(11, 3, 0);
  a {
    font-size: 38px;
    line-height: 40px;
    margin: 3px;
    color: rgb(11, 3, 0);
    text-decoration: none;

    &:hover {
      color: #f2ede3;
      transition: color 0.5s ease-in-out;
    }
  }
  p {
    font-size: 35px;
    margin: 3px;
  }

  /* margin: 0 40px; */
`;
const imageMiddleStyle = css`
  margin: 20px;
`;
const imageTopAndBottomStyle = css`
  margin: 20px;
`;

const toursHeadingStyle = css`
  background-image: linear-gradient(
    to top,
    #bfa089,
    #cbb49f,
    #d8c8b6,
    #e5dcce,
    #f4f0e7
  );
  text-align: center;
  font-size: 40px;
  padding-top: 50px;

  color: rgb(11, 3, 0);
  /* margin-top: -50px; */
  /* padding: 50px; */
  h5 {
    font-weight: 300;
    /* margin: 0; */
  }
`;

export default function Home() {
  return (
    <div css={backgroundImage}>
      <div css={heroStyle}>
        <Layout>
          <Head>
            <title>Foodies4Life</title>
            <meta name="description" content="Generated by create next app" />
          </Head>

          <div css={heroTextStyle}>
            <h1>Food Tours</h1>
            <p>Eat Like a local</p>
          </div>
        </Layout>
      </div>
      <section css={bodyStyle}>
        <div css={toursHeadingStyle}>
          <h1>Tour Highlights</h1>
          <h5>Come and eat with us!</h5>
        </div>
        <hr />
        <div css={tourSectionStyle}>
          <div css={imageTopAndBottomStyle}>
            <Image src={Thailand} width="600px" height="380px" />
          </div>
          <div css={textTourSectionStyle}>
            <a href="/tours/1">Come discover Thailand</a>
            <p>~Food Tours~</p>
          </div>
        </div>
        <hr />
        <div css={tourSectionStyle}>
          <div css={textTourSectionStyle}>
            <a href="/tours/5">Come discover London</a>
            <p>~Food Tours~</p>
          </div>
          <div css={imageMiddleStyle}>
            <Image src={London} width="600px" height="380px" />
          </div>
        </div>
        <hr />
        <div css={tourSectionStyle}>
          <div css={imageTopAndBottomStyle}>
            <Image src={Amsterdam} width="600px" height="380px" />
          </div>
          <div css={textTourSectionStyle}>
            <a href="/tours/3">Come discover Amsterdam</a>
            <p>~Food Tours~</p>
          </div>
        </div>
        <hr />
        <div css={tourSectionStyle}>
          <div css={textTourSectionStyle}>
            <a href="/tours">All Tours</a>
            <p>~Food Tours~</p>
          </div>
          <div css={imageMiddleStyle}>
            <Image src={Sunrise} width="600px" height="380px" />
          </div>
        </div>
        <hr />
      </section>
      <Footer />
    </div>
  );
}
