import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Header from '../components/Header';
import Layout from '../components/Layout';
import { readTours } from '../util/database';

const bodyStyle = css`
  background-color: rgb(163, 120, 87, 0.7);
  height: 150vh;
`;
const tourStyles = css`
  /* display: flex;
  flex-direction: row; */
  display: inline-block;
  border-radius: 5px;
  border: 1px solid #f3f7f2;
  padding: 15px;
  margin: 20px 30px;
  width: 200px;
  height: 300px;
  background-color: #f2ede3;
  /* opacity: 0.5; */

  cursor: pointer;
  a {
    text-decoration: none;
    text-align: center;
    /* margin-left: 55px; */
    color: rgb(11, 3, 0);
    font-size: 25px;
    &:hover {
      color: #b76742;
      transition: color 0.5s ease-in-out;
      text-decoration: underline;
    }
  }
  &:hover {
    box-shadow: 0px 0px 9px 7px #d5c5b2;

    transition: 0.6s ease-in-out;
  }
`;

const tourCardsStyle = css`
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
`;

const tourNameStyle = css`
  display: flex;
  justify-content: center;

  color: rgb(11, 3, 0);
`;

const imageStyle = css`
  margin: 20px 0;

  /* border-radius: 20px; */
`;

export default function Tours(props) {
  console.log('props', JSON.stringify(props));
  return (
    <div css={bodyStyle}>
      <Layout>
        <Head>
          <title>Tours</title>
          <meta
            description="A list of tours"
            content="Generated by create next app"
          />
        </Head>

        <h1 css={tourNameStyle}>All Tours</h1>
        <div css={tourCardsStyle}>
          {props.tours.map((tour) => {
            return (
              <div key={`tour-${tour.id}`}>
                <div css={tourStyles}>
                  <Link href={`/tours/${tour.id}`}>
                    <a css={tourNameStyle}>{tour.name}</a>
                  </Link>
                  <div css={imageStyle}>
                    <Image
                      src={`/images/${tour.id}.jpg`}
                      width="200"
                      height="150"
                      alt={`${tour.name} image`}
                    />
                  </div>
                  <div css={tourNameStyle}>Price: {tour.price} €</div>
                </div>
              </div>
            );
          })}
        </div>
      </Layout>
    </div>
  );
}

export async function getServerSideProps() {
  // const tours = await getTours();
  const tours = await readTours();

  return {
    props: { tours: tours },
  };
}
